SPRITE_SCALING_PLAYER = 0.25
SPRITE_SCALING_TILES = 0.8

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_TITLE = "Game not implemented!"

PHYSICS_DAMPING = 1
PHYSICS_GRAVITY = 200

PLAYER_FRICTION = 0.4
PLAYER_MASS = 0.1
PLAYER_MAX_HORIZONTAL_VELOCITY = 2000
PLAYER_MAX_VERTICAL_VELOCITY = 2000

WALL_FRICTION = 0
